Repository GoogleCloudPlatform/ai-platform-samples, pull requests merged in 2020-07, with the labels that each got.

#171 Prevent Cloud Storage bucket name from getting corrupted
  training/pytorch/structured/custom_containers/base/trainer/inputs.py
  training/pytorch/structured/custom_containers/gpu/trainer/inputs.py
  training/pytorch/structured/python_package/trainer/inputs.py
Labels: bug

#169 Add Terraform Notebooks samples
  notebooks/tools/terraform/README.md
  notebooks/tools/terraform/dlvm/instance.tf
  notebooks/tools/terraform/dlvm/main.tf
  notebooks/tools/terraform/dlvm/outputs.tf
  notebooks/tools/terraform/dlvm/variables.tf
  notebooks/tools/terraform/notebooks/instance.tf
  notebooks/tools/terraform/notebooks/instance.tf.container
  notebooks/tools/terraform/notebooks/instance.tf.cpu
  notebooks/tools/terraform/notebooks/main.tf
  notebooks/tools/terraform/notebooks/variables.tf
Labels: notebooks

#174 Refactored Horovod example
  training/horovod/Dockerfile
  training/horovod/README.md
  training/horovod/base/Dockerfile
  training/horovod/maskrcnn/Dockerfile
  training/horovod/mnist/Dockerfile
  training/horovod/scripts/train-cloud.sh
Labels: automerge
