Repository GoogleCloudPlatform/ai-platform-samples, pull requests merged in 2020-03, with the labels that each got.

#111 correct path for colab launch
  notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
Labels: automerge

#105 Migrate Iris PyTorch Notebook to AI Platform samples
  notebooks/samples/pytorch/iris_classification/serving_pytorch_models_in_ai_platform.ipynb
Labels: automerge

#112 fixes from buganizer
  notebooks/samples/optimizer/ai_platform_optimizer_multi_objective.ipynb
Labels: automerge

#114 fix error in TRAINING_PATH
  notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
Labels: automerge

#115 fix Open in Colab path
  notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
  notebooks/samples/optimizer/ai_platform_optimizer_multi_objective.ipynb
Labels: automerge

#113 Create ai_platform_sentiment_analysis.ipynb
  notebooks/samples/tensorflow/sentiment_analysis/ai_platform_sentiment_analysis.ipynb
Labels: automerge

#116 Fixed typos in AI Platform Notebook templates
  notebooks/templates/ai_platform_notebooks_template.ipynb
  notebooks/templates/ai_platform_notebooks_template_hybrid.ipynb
Labels: automerge

#104 Migrate Text Classification PyTorch Notebook to AI Platform samples
  notebooks/samples/pytorch/text_classification/text_classification_using_pytorch_and_ai_platform.ipynb
Labels: automerge

#118 Updating notebooks, minor edits
  notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
  notebooks/samples/optimizer/ai_platform_optimizer_multi_objective.ipynb
Labels: automerge

#62 Andrewferlitsch custom
  training/tensorflow/structured/base/README.md
  training/tensorflow/structured/base/trainer/custom.py
  training/tensorflow/structured/base/trainer/task.py
Labels: enhancement

#119 Revert "Andrewferlitsch custom"
  training/tensorflow/structured/base/README.md
  training/tensorflow/structured/base/trainer/custom.py
  training/tensorflow/structured/base/trainer/task.py
Labels: automerge

#110 Add tf-keras example using TF 2
  training/tensorflow/census/tf-keras/README.md
  training/tensorflow/census/tf-keras/hptuning_config.yaml
  training/tensorflow/census/tf-keras/requirements.txt
  training/tensorflow/census/tf-keras/scripts/cloud-deploy-model.sh
  training/tensorflow/census/tf-keras/scripts/train-cloud.sh
  training/tensorflow/census/tf-keras/scripts/train-local.sh
  training/tensorflow/census/tf-keras/trainer/__init__.py
  training/tensorflow/census/tf-keras/trainer/model.py
  training/tensorflow/census/tf-keras/trainer/task.py
  training/tensorflow/census/tf-keras/trainer/util.py
Labels: automerge

#122 Submitting transfer learning tutorial with tf 2 and tf hub
  notebooks/samples/tensorflow/transfer_learning/ai_platform_transfer_learning.ipynb
  notebooks/samples/tensorflow/transfer_learning/ai_platform_transfer_learning.md
Labels: automerge, enhancement

#124 Add support to check Docker container CPU idle value
  notebooks/tools/auto-shutdown/ashutdown
Labels: automerge
